### ISSUE TITLE
the app simply refuses to connect

### ISSUE THREAD

**Issue by julianpoelmann** [Curtis-VL/HeartRateOnStream-OSC#1]

**Comment by julianpoelmann** [comment]
oh wait it didnt let me write the rest. the details match and when matching the port on obs it works but when i match the port with the tool it just refuses to connect

**Comment by Curtis-VL** [comment]
Could your firewall be blocking it? :o

**Comment by julianpoelmann** [comment]
ima check but it shouldnt, it worked fine in obs itself

**Comment by julianpoelmann** [comment]
there's no firewall rule, also your discord info is outdated in the readme

**Comment by Curtis-VL** [comment]
Note if OBS is open the port may be in use!

**Comment by julianpoelmann** [comment]
obs wasnt open

**Comment by Curtis-VL** [comment]
Closed due to inactivity
