### ISSUE TITLE
After purchase from googleplay, app doesnt connect to websocket server. 

### ISSUE THREAD

**Issue by Dominix1910** [Curtis-VL/HeartRateOnStream-OSC#2]
Hi.
I've been using this app for a while, but recently i cant connect it on my phone.
App on my phone connect with my watch, but when I want to connect app with my PC it doesnt. I have OBS ver 30, I scanned websocket connection info via QR code, and every time i press connect it doesn't.
Before I was using free version, but as I use phone from time to time while using an app and forgot to keep it running with screen on, after buying it from google store it doesnt work anymore.
I have Pixel 8 Pro, I set hotspot on my PC (win 11) to connect Phone with PC via Wi-Fi.

**Comment by Curtis-VL** [comment]
Hi there,

The setup you have sounds a little confusing.

To simply things, there's no need for hotspot stuff. Simply make sure your phone and PC are on the same network, ethernet or wireless is fine for the PC so long as they're both connected to the same router.

I'm not sure I understand what QR code you're using. When you launch HeartRateOnStream-OSC it'll provide you with the correct IP, there's no need to have OBS running as this may interfere.

I can't confirm for the Pixel 8, but I'm using a Pixel 6 and Pixel Watch with this fine to this date, though I am still using the free version of Heartrate On Stream. :)

**Comment by Dominix1910** [comment]
I have been using it for a while like this and had no problems at all. I have to enable hotspot on my PC as I have no wifi coverage where my PC is.
![image](https://github.com/Curtis-VL/HeartRateOnStream-OSC/assets/163021823/de92a9b1-4a91-432f-94cb-9d4adb3c5059)

So i setup websocket server in obs, then on my phone in the app i scan QR code to get all information, save and I can't connect. Not sure what is wrong to make it work again.

**Comment by Dominix1910** [comment]
Ok, I have found a fix for my problem. I use google VPN and when this is ON, app cannot connect with websocket server in OBS, when i turn off VPN, it is working fine :)

**Comment by Curtis-VL** [comment]
Closed, resolved!
