### ISSUE TITLE
Measurement inconsistent after App update

### ISSUE THREAD

**Issue by apxLegi** [Curtis-VL/HeartRateOnStream-OSC#3]
After a recent app update from HR on Stream, the app luckily finally stopped randomly losing the connection because another app is trying to read heartrate data or the scan intervall is set to once every 10 minutes!

After that though, the OSC program jumps between seemingly two values that got read, there is the right heartrate inbetween and another value that got read way in the past!

https://github.com/Curtis-VL/HeartRateOnStream-OSC/assets/114291917/49b903ca-ea7c-4dd2-96d1-3f034dbe2585

**Comment by Curtis-VL** [comment]
Oh boy... That looks fun.

I'll dig into this and see what I can do! I'd actually like to make a bit of simple UI too in all honesty, something nicer and more obvious than a terminal. :)

We'll see what can be done about this specific issue!

**Comment by apxLegi** [comment]
Eyy cool!! Thanks a lot for putting the effort into it :D

**Comment by Curtis-VL** [comment]
Helloooooo!

Can you check out the latest update and see if this issue persists?

I've made some changes that should make this a none-issue now hopefully!

https://github.com/Curtis-VL/HeartRateOnStream-OSC/releases

**Comment by apxLegi** [comment]
It worked great! Thank you for the fix!!
I've been using the program for a long time now and I always admire how simple it is and how well it works!

Thanks a lot!! c:
