### ISSUE TITLE
App contains an Error

### ISSUE THREAD

**Issue by Cedric-V-Piehl** [Curtis-VL/HeartRateOnStream-OSC#5]
The App closes it self directly.
The old V. 1.5.0 does open but does not connect to Galaxy Watch 4.
I am on a rooted Samsung S10 which runs Android 12 OneUI 4.1

**Comment by Cedric-V-Piehl** [comment]
![Screenshot_20240720_231644_Device care.jpg](https://github.com/user-attachments/assets/05a6b549-bf41-4ecf-8bbe-2781ca2a974a)

It's on german but what it basically says is that the App contains an error and that I should try to Update is as Soon as the dev fixes it.

**Comment by Curtis-VL** [comment]
You'll need to contact the app developers for this I'm afraid!
This application just pretends to be OBS for the purpose of intercepting the heart rate data, I can't help with the app I'm afraid. :)
