### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by Sausageinforest** [Curtis-VL/HeartRateOnStream-OSC#6]
Will there be a version for Linux? If so, that would be great, because it would be possible to use this application standalone, without a PC, just by running this program directly on the standalone VR headset like Quest or Pico in Termux (command line emulator).

**Comment by Curtis-VL** [comment]
I believe VRChat OSC isn't supported on standalone devices yet, only on PC. :)

**Comment by Sausageinforest** [comment]
I think you are wrong, I for example already used SlimeVR trackers and Viso in standalone mode, without PC. VRChat on standalone headset supports OSC. If anything I'm not forcing you to do it, your project is good without it.

**Comment by Curtis-VL** [comment]
Oh! I didn't know that, neat!

In theory it should already run on Linux through Mono? Unless there's something incompatible. I don't have a Linux desktop to test any changes on for a dedicated Linux build I'm afraid, also as this is written in .NET Framework it doesn't natively support Linux anyway outside of Mono.

**Comment by Sausageinforest** [comment]
I didn't even realize it was written in .net( sorry for the inconvenience. All the best

**Comment by Curtis-VL** [comment]
All good! Re-open this issue if there's anything specific I can try to help with! :)
